name: Export my notion workspace

on:
  schedule:
    - cron: "0 */24 * * *"  # Call the export every 24 hours
  workflow_dispatch: {}

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: igor-kupczynski/notion-exporter@v1.0.2
        with:
          pages: "Apriori-Algorithm-db01a4ff834648e68c2bdb4fe8edf979"  # Identifier  
          output-dir: apriori_algorithm
          notion-token: ${{ secrets.NOTION_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
